import type { CapacitorConfig } from "@capacitor/cli";

const config: CapacitorConfig = {
  appId: "com.foreperformancesystems.forge",
  appName: "Forge",
  webDir: "dist/public",
  // Local dev convenience: point the native shell at the Vite dev server
  // instead of the bundled webDir by setting CAP_SERVER_URL before `cap run`
  // (e.g. CAP_SERVER_URL=http://192.168.1.20:5173). Unset in every built
  // artifact -- CI never sets this, so release builds always load the
  // bundled dist/public, never a live dev server.
  ...(process.env.CAP_SERVER_URL
    ? { server: { url: process.env.CAP_SERVER_URL, cleartext: true } }
    : {}),
  ios: {
    // getUserMedia inside WKWebView requires the WebView's own content to be
    // served over a secure context. Capacitor's default capacitor://
    // scheme already counts as secure, but contentInset + limitsNavigation
    // matter less here than making sure this file stays the single source
    // of truth for the bundle id / scheme so ios/App/App/capacitor.config.json
    // (generated by `cap sync`) never drifts from it.
    contentInset: "automatic",
  },
  android: {
    allowMixedContent: false,
  },
  plugins: {
    PushNotifications: {
      // Otherwise a push that arrives while the app is already open and
      // foregrounded shows nothing at all -- iOS suppresses foreground
      // banners by default unless the app explicitly opts in.
      presentationOptions: ["badge", "sound", "banner", "list"],
    },
    SplashScreen: {
      // Held up until native-bootstrap.ts explicitly calls hide() once
      // React has actually mounted -- the plugin's own default timer would
      // otherwise auto-dismiss the splash as soon as the WebView's page
      // load event fires, which on a slow cold start can land well before
      // the app shell is actually ready to show, flashing an empty dark
      // screen in between.
      launchAutoHide: false,
      backgroundColor: "#0B0B0F",
      androidSplashResourceName: "splash",
      androidScaleType: "CENTER_CROP",
    },
  },
};

export default config;
