// First-pass draft text for the admin-editable Terms of Service, Privacy
// Policy, Biometric Waiver, and Parental Notice (see shared/schema.ts
// legalDocuments). Grounded in what Forge actually does today --
// camera-based tracking, the AI features, the wellness/nutrition/injury
// data it collects, the age-tier system built alongside this -- not
// generic boilerplate. Still explicitly a draft: nothing here has been
// reviewed by a lawyer, and none of it is wired into any live signup or
// delivery flow (that's legalAgreement's job, a separate, shorter document
// actually shown at signup). See getComplianceReportData's own "not yet
// reviewed"/"not yet built" list for the same caveats stated as structured
// data, not just a comment here -- both the biometric_waiver consent_type
// and the parental-notice delivery this file's PARENTAL_NOTICE_DRAFT is
// for were unwritten until now, and this is a first pass, not a decision
// that either is ready to go live.

const DRAFT_NOTICE =
  "DRAFT -- not reviewed by a lawyer. This document is a starting point for legal review, not a finished, reliable Terms of Service. Do not treat it as legally sufficient until counsel has reviewed and approved it.";

export const TERMS_OF_SERVICE_DRAFT = `${DRAFT_NOTICE}

FORGE -- TERMS OF SERVICE (DRAFT)

1. ACCEPTANCE OF TERMS
By creating a Forge account or using the Forge app or website ("Forge," "the Service"), you agree to these Terms. If you don't agree, don't use the Service.

2. WHAT FORGE IS
Forge is an athletic performance platform for coaches and athletes. It uses camera-based tracking (ARKit on iOS, MediaPipe on web/Android) to estimate barbell velocity, jump height, sprint times, and movement mechanics from video captured on the user's own device; it also lets athletes and coaches log wellness check-ins, nutrition, injuries, testing/combine numbers, and training programs, and offers AI-generated program suggestions, form-check feedback, and a coaching chat assistant.

3. NOT MEDICAL OR PROFESSIONAL ADVICE
Nothing in Forge -- including AI-generated suggestions, tracked metrics, or form-fault flags -- is medical advice, a diagnosis, or a substitute for a qualified coach, athletic trainer, or physician. Camera-based tracking is an estimate, not a clinical or laboratory-grade measurement, and should be treated accordingly. Athletes and coaches are responsible for using their own judgment about what's safe, and for stopping any activity that causes pain or feels unsafe.

4. ELIGIBILITY AND AGE
Forge sorts accounts into age tiers and applies different signup rules to each (see the Privacy Policy for the full description). Athletes under 13 cannot self-register; an account for an athlete under 13 may only be created by a coach or program acting as the athlete's registering agent. By creating an account, you confirm the age information you provide is accurate.

5. YOUR ACCOUNT
You're responsible for keeping your login credentials confidential and for all activity under your account. Tell us if you believe your account has been compromised. You can permanently delete your account at any time from within the app; deletion removes your account and, for athletes, the video files tied to it.

6. YOUR CONTENT
You keep ownership of the video, performance data, and other content you or your athletes submit ("Your Content"). By submitting it, you grant Forge a license to store, process, and display it back to you and (for an athlete's data) their coach, solely to provide the Service. We don't sell Your Content. Don't upload video or data about someone else without their (or, for a minor, their parent/coach-as-agent's) permission.

7. AI FEATURES
Forge's AI features (program suggestions, form-check feedback, the coaching chat assistant) are generated by a third-party AI model and can be wrong, incomplete, or generic. They're intended to support a human coach's judgment, not replace it. Don't rely on an AI-generated suggestion as the sole basis for a training or medical decision.

8. SUBSCRIPTIONS AND PAYMENTS
Forge does not currently charge for access. If and when paid plans launch, separate terms covering pricing, billing, and cancellation will apply, and platform rules (e.g. Apple's or Google's in-app purchase requirements) will govern how any in-app purchase is billed.

9. PROHIBITED CONDUCT
Don't use Forge to harass anyone, upload content you don't have the right to share, attempt to access another person's account or another coach's roster without authorization, or interfere with the Service's normal operation.

10. TERMINATION
We may suspend or terminate an account that violates these Terms. You may stop using Forge and delete your account at any time.

11. DISCLAIMER OF WARRANTIES
The Service is provided "as is," without warranties of any kind, to the fullest extent the law allows.

12. LIMITATION OF LIABILITY
To the fullest extent the law allows, Forge Performance Systems LLC is not liable for indirect, incidental, or consequential damages arising from use of the Service, including injuries arising from training activity -- athletic training carries inherent physical risk that using this app does not create or increase.

13. ASSUMPTION OF RISK
Athletic training -- including weightlifting, sprinting, jumping, and other movements tracked or programmed through Forge -- carries inherent risks of physical injury, up to and including severe injury or death. By using the Service, you expressly acknowledge and assume these risks. As stated in Section 3, Forge's camera-based tracking, AI-generated suggestions, and form-fault flags are informational aids only; they do not guarantee safety, correct execution of any movement, or the absence of injury. A coach using the Service remains responsible for appropriately supervising and modifying training for their own athletes.

14. INDEMNIFICATION
You agree to defend, indemnify, and hold harmless Forge Performance Systems LLC, its affiliates, officers, and employees from any claim, damage, liability, or expense (including reasonable attorneys' fees) arising from: (a) your use of the Service, (b) your violation of these Terms, or (c) injury or harm arising from athletic training you directed, supervised, or performed. This section does not extend to a claim arising from Forge's own gross negligence or willful misconduct. [Placeholder -- confirm with counsel whether and how this section can apply where the person being asked to indemnify is a minor athlete or their parent/guardian; several states limit or void an indemnification obligation imposed on a minor.]

15. DISPUTE RESOLUTION AND BINDING ARBITRATION
Except as set out below, any dispute, claim, or controversy arising out of or relating to these Terms or your use of the Service will be resolved by binding arbitration administered by the American Arbitration Association under its Consumer Arbitration Rules, instead of in court, except that either party may bring an individual claim in small-claims court where eligible. You and Forge each waive any right to a jury trial.

Class Action Waiver: Any arbitration or proceeding will be conducted only on an individual basis, not as a class, collective, or representative action, to the fullest extent the law allows.

Minors: This arbitration and class-action-waiver section applies only to a user who is 18 or older at the time a dispute arises. For a dispute involving an athlete under 18, this section does not apply, and the dispute may instead be brought in a court of competent jurisdiction, unless a parent or legal guardian separately and knowingly agrees to arbitration on the athlete's behalf in a signed writing. [Placeholder -- confirm this carve-out with counsel; state law on arbitration involving minors varies and this approach has not been reviewed.]

16. GOVERNING LAW
These Terms and any action related to them are governed by the laws of the State of Arizona, without regard to its conflict-of-laws provisions. Exclusive jurisdiction and venue for any dispute not subject to arbitration under Section 15 lie in the state and federal courts located in Maricopa County, Arizona.

17. CHANGES TO THESE TERMS
We may update these Terms; continued use after an update means you accept the revised Terms. Material changes will be reflected in the version an athlete is asked to accept at signup.

18. CONTACT
[Placeholder -- add a real support/contact email once one exists.]`;

export const PRIVACY_POLICY_DRAFT = `${DRAFT_NOTICE}

FORGE -- PRIVACY POLICY (DRAFT)

1. OVERVIEW
This Privacy Policy describes what Forge Performance Systems LLC ("Forge") collects through the Forge app and website, why, and what control you have over it.

2. INFORMATION WE COLLECT
- Account/profile: name, email, role, sport, position, age/date of birth, height, weight, season phase.
- Performance data captured via on-device camera tracking: bar-path velocity, range of motion, jump height, sprint splits, joint angles, and similar biomechanical metrics, computed from video processed on the athlete's own device.
- Video: form-check clips an athlete chooses to save, and skill-drill clips, both opt-in per recording.
- Wellness and health-adjacent data: daily sleep/soreness/stress/hydration self-reports, injury history, goniometer joint-mobility readings, movement-screen results.
- Nutrition data an athlete chooses to log, including photos of meals when using photo-based logging.
- Usage data: login timestamps, device/app version, and similar technical data needed to operate and secure the Service.

3. HOW WE USE INFORMATION
To provide the Service: running programs, showing tracked metrics and trends to an athlete and their coach, generating AI program/coaching suggestions, sending notifications an athlete or coach has opted into, and platform-level aggregate analytics (always with names, emails, and team affiliation removed -- see Section 7).

4. BIOMETRIC INFORMATION
The camera-tracked performance metrics and joint-angle data above are derived from video processed on-device; raw video is uploaded only when an athlete explicitly chooses to save a clip. We do not sell biometric information. Some states (for example, Illinois' Biometric Information Privacy Act) impose specific requirements on collecting and retaining this kind of data, including written consent and a public retention schedule -- Forge's specific compliance posture under these laws has not yet been finalized by counsel, and this section will be updated once it has.

5. CHILDREN'S PRIVACY
Forge sorts accounts by age into three tiers. Athletes under 13 cannot create their own account; an account for an athlete under 13 may only be set up by a coach or program acting as the athlete's registering agent, and raw video for these accounts is automatically deleted after a limited retention window (numeric performance data is not). Athletes 13-17 may self-register but get privacy-protective defaults. This structure is designed with the intent of the Children's Online Privacy Protection Act (COPPA) in mind; it has not yet been reviewed by counsel for actual COPPA compliance.

6. HOW LONG WE KEEP INFORMATION
Video for Tier 1 (under 13) and Tier 2 (13-17) accounts is automatically deleted after a configured retention window; the numeric metrics derived from it are kept. Other account data is kept until an account is deleted, at which point it is permanently removed (see Section 9).

7. HOW WE SHARE INFORMATION
We do not sell personal information. We share information with:
- Service providers who process data on our behalf to run the Service: our AI provider (Anthropic) for AI-generated features, our email provider (Resend) for account and notification emails, and public food-database lookups (Open Food Facts, USDA FoodData Central) for nutrition logging.
- Apple and Google, as required to operate push notifications and distribute the app through their platforms.
- A coach, for their own roster athletes' data, as the core function of the Service.
- Platform-wide aggregate analytics an admin can view are stripped of name, email, and team before an admin ever sees them.

8. DATA SECURITY
We use industry-standard measures (encrypted connections, access controls, audit logging of staff access to individual athlete video/records) to protect your information, but no system is perfectly secure.

9. YOUR RIGHTS AND CHOICES
You can review and correct your profile information in the app, and permanently delete your account (and, for athletes, its video files) at any time from within the app. Depending on where you live, you may have additional rights under applicable state privacy law; contact us to exercise them.

10. CHANGES TO THIS POLICY
We may update this Policy as the Service changes; material changes will be reflected here with an updated date once this document has real version tracking.

11. CONTACT
[Placeholder -- add a real privacy-contact email once one exists.]`;

// A biometric waiver is its own legal instrument, separate from the general
// Privacy Policy section that just mentions this data exists (see Section 4
// above) -- most state biometric laws (Illinois' BIPA is the model this
// draft follows most closely, since it's the most specific and the most
// litigated) expect a standalone written release naming exactly what's
// collected, why, how long it's kept, and an explicit "I consent," not a
// clause buried in a longer privacy policy. consentRecords.consentType
// already has "biometric_waiver" as a real value (see shared/schema.ts) --
// this is the document text that type has never had until now.
export const BIOMETRIC_WAIVER_DRAFT = `${DRAFT_NOTICE}

FORGE -- BIOMETRIC INFORMATION CONSENT AND RELEASE (DRAFT)

1. WHAT THIS IS
This is a release specifically for the biometric and biometric-adjacent information described below, separate from and in addition to Forge's general Terms of Service and Privacy Policy. Signing (or, for an athlete under 18, a parent/guardian or coach-as-agent signing on the athlete's behalf) means you understand and consent to the collection described here.

2. WHAT'S COLLECTED
Forge's camera-based tracking (ARKit on iOS, MediaPipe on web/Android) processes video of the athlete's body in motion, captured on the athlete's own device, to compute: joint angles and body-segment positions, bar-path/barbell velocity, jump height and ground-contact time, sprint splits, and similar movement-mechanics metrics. Some of this processing is a form of biometric identifier or biometric information under laws like Illinois' Biometric Information Privacy Act (BIPA) and comparable state statutes. Raw video is stored only when the athlete (or their coach, recording on their behalf) explicitly chooses to save a clip -- tracking metrics are computed whether or not the clip itself is kept.

3. WHY IT'S COLLECTED
Solely to provide the Service: showing an athlete and their coach tracked performance metrics and trends, flagging movement-mechanics faults for coaching purposes, and (only for saved clips) letting an athlete or coach review the footage itself. This data is not used for facial recognition, identity verification, or any purpose other than athletic performance tracking as described here.

4. RETENTION AND DESTRUCTION
Raw video for Tier 1 (under 13) accounts is automatically deleted 30 days after capture; for Tier 2 (13-17) accounts, 90 days after capture. These windows are current engineering defaults, not figures set by counsel or required by any specific statute -- see the note below. Numeric metrics computed from that video (bar-path velocity, joint angles, jump height, and similar) are NOT deleted on this schedule; they are retained as ordinary performance history, the same as a hand-recorded stopwatch time would be, until the athlete's account itself is deleted. Adult (Tier 3, 18+) accounts have no automatic video deletion window -- video is retained until the athlete deletes it individually or deletes their account. Deleting an account permanently removes all of that account's stored video immediately, for every tier. [Placeholder -- confirm with counsel that stating these operational windows here satisfies BIPA's requirement for a published retention schedule, whether the 30/90-day figures themselves should change, and whether a maximum age-independent retention ceiling should also be added.]

5. NO SALE, NO UNRELATED DISCLOSURE
Forge does not sell, lease, trade, or otherwise profit from this data. It is shared only with the athlete's own coach (as the core function of the Service) and with the service providers named in the Privacy Policy's "How We Share Information" section, solely to operate the Service.

6. YOUR RIGHTS
You (or, for a minor, their parent/guardian) may ask what biometric data Forge holds for that athlete, and may request its deletion by deleting the athlete's account, which removes stored video immediately -- tracked numeric metrics already logged as part of training history are retained the same way any other workout record is, unless a specific request for further deletion is made. [Placeholder -- confirm this matches what BIPA and any other applicable state law actually requires before this is treated as a complete rights statement.]

7. CONSENT
By signing, you confirm you've read and understood this release and consent to the collection, use, and retention described above, for as long as the associated Forge account remains active or until consent is withdrawn by deleting the account.

[Placeholder -- signature/date capture, and the specific state-law citations this release is meant to satisfy, need to be finalized with counsel before this is used to collect a real signature.]`;

// Addressed to a parent/guardian, not the athlete -- distinct from every
// other document in this file, which speaks to whoever's using the app.
// This is what shared/privacy-tiers.ts's GUARDIAN_NOTICE_LIVE flag and
// users.requiresGuardianNotice exist to eventually deliver: real content
// for the "notice" half of "parental notice," which the compliance report
// has flagged as unwritten until now. Scoped to Tier 2 (13-17, who can
// self-register today) -- Tier 1 (under 13) never reaches this document at
// all, since that tier can't self-register in the first place and goes
// through coach_coppa_consent instead, given by the registering coach as
// the athlete's agent. [Placeholder -- confirm with counsel that Tier 2
// even needs a document called a "parental notice" in the first place, as
// opposed to just the existing self-registration flow; the age at which a
// state expects parental involvement for a minor's data varies, and this
// draft assumes 13-17 warrants one without that having been confirmed
// against real law.]
export const PARENTAL_NOTICE_DRAFT = `${DRAFT_NOTICE}

FORGE -- NOTICE TO PARENT OR GUARDIAN (DRAFT)

1. WHY YOU'RE SEEING THIS
Your teen (age 13-17) created their own Forge account, using either a coach's invite code or a direct signup -- at this age, Forge lets a teen register themselves rather than requiring a parent to do it for them. This notice is what a parent or guardian would receive as a result, so you know the account exists and what it involves before you'd normally need to ask.

2. WHAT FORGE IS
Forge is an athletic performance platform coaches and athletes use for training programs, wellness check-ins, and camera-based movement tracking (bar-path velocity, jump height, sprint times, and similar metrics computed from video captured on your teen's own device). See the Privacy Policy for the full description of what it collects and why.

3. WHAT'S COLLECTED ABOUT YOUR TEEN
Account/profile information (name, email, sport, position, age), training data their coach assigns and they log, wellness self-reports (sleep, soreness, stress), and -- only when your teen explicitly chooses to save a clip -- video captured during a tracked movement. See the Privacy Policy's "Biometric Information" section for what's collected from that video specifically.

4. WHO CAN SEE IT
Your teen's own coach can see their training data and tracked metrics, the same way a coach would see it on a clipboard or a whiteboard. Forge staff can access it only as described in the Privacy Policy (support, legal compliance, or safety review). Nobody else -- not other athletes, not other coaches outside your teen's own -- can see it.

5. YOUR ROLE AND YOUR OPTIONS
You don't need to do anything for the account to keep working. If you'd rather review what's on file, ask questions, or have the account deleted, you (or your teen) can do that -- see Section 9 of the Privacy Policy ("Your Rights and Choices") for how. Deleting the account removes it and any saved video permanently.

6. QUESTIONS
[Placeholder -- add a real contact email once one exists, the same one referenced in the Terms of Service and Privacy Policy.]

[Placeholder -- how and when this notice is actually delivered to a parent (email at signup? a coach-relayed message? something else) is exactly what GUARDIAN_NOTICE_LIVE and the "not yet built" delivery channel in the compliance report refer to -- this is the content that channel would send, not a decision that the channel itself is ready.]`;
