// First-pass draft text for the admin-editable Terms of Service and Privacy
// Policy (see shared/schema.ts legalDocuments). Grounded in what Forge
// actually does today -- camera-based tracking, the AI features, the
// wellness/nutrition/injury data it collects, the age-tier system built
// alongside this -- not generic boilerplate. Still explicitly a draft:
// nothing here has been reviewed by a lawyer, and it is not wired into the
// signup flow (that's legalAgreement's job, a separate, shorter document).
// See getComplianceReportData's own "not yet reviewed" list for the same
// caveat stated as structured data, not just a comment here.

const DRAFT_NOTICE =
  "DRAFT -- not reviewed by a lawyer. This document is a starting point for legal review, not a finished, reliable Terms of Service. Do not treat it as legally sufficient until counsel has reviewed and approved it.";

export const TERMS_OF_SERVICE_DRAFT = `${DRAFT_NOTICE}

FORGE -- TERMS OF SERVICE (DRAFT)

1. ACCEPTANCE OF TERMS
By creating a Forge account or using the Forge app or website ("Forge," "the Service"), you agree to these Terms. If you don't agree, don't use the Service.

2. WHAT FORGE IS
Forge is an athletic performance platform for coaches and athletes. It uses camera-based tracking (ARKit on iOS, MediaPipe on web/Android) to estimate barbell velocity, jump height, sprint times, and movement mechanics from video captured on the user's own device; it also lets athletes and coaches log wellness check-ins, nutrition, injuries, testing/combine numbers, and training programs, and offers AI-generated program suggestions, form-check feedback, and a coaching chat assistant.

3. NOT MEDICAL OR PROFESSIONAL ADVICE
Nothing in Forge -- including AI-generated suggestions, tracked metrics, or form-fault flags -- is medical advice, a diagnosis, or a substitute for a qualified coach, athletic trainer, or physician. Camera-based tracking is an estimate, not a clinical or laboratory-grade measurement, and should be treated accordingly. Athletes and coaches are responsible for using their own judgment about what's safe, and for stopping any activity that causes pain or feels unsafe.

4. ELIGIBILITY AND AGE
Forge sorts accounts into age tiers and applies different signup rules to each (see the Privacy Policy for the full description). Athletes under 13 cannot self-register; an account for an athlete under 13 may only be created by a coach or program acting as the athlete's registering agent. By creating an account, you confirm the age information you provide is accurate.

5. YOUR ACCOUNT
You're responsible for keeping your login credentials confidential and for all activity under your account. Tell us if you believe your account has been compromised. You can permanently delete your account at any time from within the app; deletion removes your account and, for athletes, the video files tied to it.

6. YOUR CONTENT
You keep ownership of the video, performance data, and other content you or your athletes submit ("Your Content"). By submitting it, you grant Forge a license to store, process, and display it back to you and (for an athlete's data) their coach, solely to provide the Service. We don't sell Your Content. Don't upload video or data about someone else without their (or, for a minor, their parent/coach-as-agent's) permission.

7. AI FEATURES
Forge's AI features (program suggestions, form-check feedback, the coaching chat assistant) are generated by a third-party AI model and can be wrong, incomplete, or generic. They're intended to support a human coach's judgment, not replace it. Don't rely on an AI-generated suggestion as the sole basis for a training or medical decision.

8. SUBSCRIPTIONS AND PAYMENTS
Forge does not currently charge for access. If and when paid plans launch, separate terms covering pricing, billing, and cancellation will apply, and platform rules (e.g. Apple's or Google's in-app purchase requirements) will govern how any in-app purchase is billed.

9. PROHIBITED CONDUCT
Don't use Forge to harass anyone, upload content you don't have the right to share, attempt to access another person's account or another coach's roster without authorization, or interfere with the Service's normal operation.

10. TERMINATION
We may suspend or terminate an account that violates these Terms. You may stop using Forge and delete your account at any time.

11. DISCLAIMER OF WARRANTIES
The Service is provided "as is," without warranties of any kind, to the fullest extent the law allows.

12. LIMITATION OF LIABILITY
To the fullest extent the law allows, Forge Athletic Technologies LLC is not liable for indirect, incidental, or consequential damages arising from use of the Service, including injuries arising from training activity -- athletic training carries inherent physical risk that using this app does not create or increase.

13. GOVERNING LAW
[Placeholder -- to be set once the company's home jurisdiction is finalized.]

14. CHANGES TO THESE TERMS
We may update these Terms; continued use after an update means you accept the revised Terms. Material changes will be reflected in the version an athlete is asked to accept at signup.

15. CONTACT
[Placeholder -- add a real support/contact email once one exists.]`;

export const PRIVACY_POLICY_DRAFT = `${DRAFT_NOTICE}

FORGE -- PRIVACY POLICY (DRAFT)

1. OVERVIEW
This Privacy Policy describes what Forge Athletic Technologies LLC ("Forge") collects through the Forge app and website, why, and what control you have over it.

2. INFORMATION WE COLLECT
- Account/profile: name, email, role, sport, position, age/date of birth, height, weight, season phase.
- Performance data captured via on-device camera tracking: bar-path velocity, range of motion, jump height, sprint splits, joint angles, and similar biomechanical metrics, computed from video processed on the athlete's own device.
- Video: form-check clips an athlete chooses to save, and skill-drill clips, both opt-in per recording.
- Wellness and health-adjacent data: daily sleep/soreness/stress/hydration self-reports, injury history, goniometer joint-mobility readings, movement-screen results.
- Nutrition data an athlete chooses to log, including photos of meals when using photo-based logging.
- Usage data: login timestamps, device/app version, and similar technical data needed to operate and secure the Service.

3. HOW WE USE INFORMATION
To provide the Service: running programs, showing tracked metrics and trends to an athlete and their coach, generating AI program/coaching suggestions, sending notifications an athlete or coach has opted into, and platform-level aggregate analytics (always with names, emails, and team affiliation removed -- see Section 7).

4. BIOMETRIC INFORMATION
The camera-tracked performance metrics and joint-angle data above are derived from video processed on-device; raw video is uploaded only when an athlete explicitly chooses to save a clip. We do not sell biometric information. Some states (for example, Illinois' Biometric Information Privacy Act) impose specific requirements on collecting and retaining this kind of data, including written consent and a public retention schedule -- Forge's specific compliance posture under these laws has not yet been finalized by counsel, and this section will be updated once it has.

5. CHILDREN'S PRIVACY
Forge sorts accounts by age into three tiers. Athletes under 13 cannot create their own account; an account for an athlete under 13 may only be set up by a coach or program acting as the athlete's registering agent, and raw video for these accounts is automatically deleted after a limited retention window (numeric performance data is not). Athletes 13-17 may self-register but get privacy-protective defaults. This structure is designed with the intent of the Children's Online Privacy Protection Act (COPPA) in mind; it has not yet been reviewed by counsel for actual COPPA compliance.

6. HOW LONG WE KEEP INFORMATION
Video for Tier 1 (under 13) and Tier 2 (13-17) accounts is automatically deleted after a configured retention window; the numeric metrics derived from it are kept. Other account data is kept until an account is deleted, at which point it is permanently removed (see Section 9).

7. HOW WE SHARE INFORMATION
We do not sell personal information. We share information with:
- Service providers who process data on our behalf to run the Service: our AI provider (Anthropic) for AI-generated features, our email provider (Resend) for account and notification emails, and public food-database lookups (Open Food Facts, USDA FoodData Central) for nutrition logging.
- Apple and Google, as required to operate push notifications and distribute the app through their platforms.
- A coach, for their own roster athletes' data, as the core function of the Service.
- Platform-wide aggregate analytics an admin can view are stripped of name, email, and team before an admin ever sees them.

8. DATA SECURITY
We use industry-standard measures (encrypted connections, access controls, audit logging of staff access to individual athlete video/records) to protect your information, but no system is perfectly secure.

9. YOUR RIGHTS AND CHOICES
You can review and correct your profile information in the app, and permanently delete your account (and, for athletes, its video files) at any time from within the app. Depending on where you live, you may have additional rights under applicable state privacy law; contact us to exercise them.

10. CHANGES TO THIS POLICY
We may update this Policy as the Service changes; material changes will be reflected here with an updated date once this document has real version tracking.

11. CONTACT
[Placeholder -- add a real privacy-contact email once one exists.]`;
