import PDFDocument from "pdfkit";
import { TESTING_METRICS } from "@shared/testing-metrics";

type Athlete = {
  name: string;
  age?: number | null;
  heightIn?: number | null;
  bodyWeightLbs?: number | null;
  sport?: string | null;
  position?: string | null;
} & Record<(typeof TESTING_METRICS)[number]["key"], number | null | undefined>;

type ProgressSummary = {
  recentPRs: { exerciseName: string; weight: number; unit: string; reps: string; date: string }[];
};

function formatHeight(heightIn: number | null | undefined) {
  if (heightIn == null) return null;
  const feet = Math.floor(heightIn / 12);
  const inches = heightIn % 12;
  return `${feet}'${inches}"`;
}

const ORANGE = "#F65B23";
const DARK = "#111111";
const GREY = "#666666";

/** One-page PDF snapshot of an athlete's bio, testing/combine numbers, and
 * recent PRs -- built for the athlete (or their coach) to hand to a
 * recruiter, not hosted anywhere. Returns a Buffer so the route can set its
 * own headers rather than piping a stream. */
export function buildRecruitingProfilePdf(
  athlete: Athlete,
  summary: ProgressSummary,
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "LETTER", margin: 50 });
    const chunks: Buffer[] = [];
    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    doc.rect(0, 0, doc.page.width, 90).fill(ORANGE);
    doc
      .fillColor("#ffffff")
      .fontSize(24)
      .font("Helvetica-Bold")
      .text("FORGE", 50, 30);
    doc
      .fontSize(10)
      .font("Helvetica")
      .text("Athlete Recruiting Profile", 50, 60);

    doc.moveDown(3);
    doc.fillColor(DARK).fontSize(22).font("Helvetica-Bold").text(athlete.name);

    const bioLine = [athlete.sport, athlete.position].filter(Boolean).join(" · ");
    if (bioLine) {
      doc.fillColor(GREY).fontSize(12).font("Helvetica").text(bioLine);
    }

    doc.moveDown(0.5);
    const bioStats = [
      athlete.age != null ? `Age ${athlete.age}` : null,
      formatHeight(athlete.heightIn) ? `Height ${formatHeight(athlete.heightIn)}` : null,
      athlete.bodyWeightLbs != null ? `Weight ${athlete.bodyWeightLbs} lbs` : null,
    ].filter(Boolean);
    if (bioStats.length) {
      doc.fillColor(GREY).fontSize(11).text(bioStats.join("   |   "));
    }

    const testingRows = TESTING_METRICS.filter((m) => athlete[m.key] != null);
    if (testingRows.length) {
      doc.moveDown(1.5);
      doc.fillColor(ORANGE).fontSize(13).font("Helvetica-Bold").text("TESTING / COMBINE");
      doc.moveDown(0.3);
      doc.moveTo(50, doc.y).lineTo(doc.page.width - 50, doc.y).strokeColor(ORANGE).stroke();
      doc.moveDown(0.5);

      const colWidth = (doc.page.width - 100) / 2;
      let col = 0;
      let rowStartY = doc.y;
      for (const m of testingRows) {
        const x = 50 + col * colWidth;
        doc.fillColor(GREY).fontSize(10).font("Helvetica").text(m.label, x, rowStartY);
        doc
          .fillColor(DARK)
          .fontSize(14)
          .font("Helvetica-Bold")
          .text(`${athlete[m.key]} ${m.unit}`, x, rowStartY + 13);
        col++;
        if (col === 2) {
          col = 0;
          rowStartY += 40;
        }
      }
      doc.y = rowStartY + (col === 0 ? 0 : 40) + 10;
    }

    if (summary.recentPRs.length) {
      doc.moveDown(1);
      doc.fillColor(ORANGE).fontSize(13).font("Helvetica-Bold").text("RECENT PRS");
      doc.moveDown(0.3);
      doc.moveTo(50, doc.y).lineTo(doc.page.width - 50, doc.y).strokeColor(ORANGE).stroke();
      doc.moveDown(0.5);

      for (const pr of summary.recentPRs.slice(0, 8)) {
        doc
          .fillColor(DARK)
          .fontSize(11)
          .font("Helvetica")
          .text(`${pr.exerciseName}`, 50, doc.y, { continued: true, width: 300 })
          .font("Helvetica-Bold")
          .text(`  ${pr.weight} ${pr.unit} x ${pr.reps}`, { continued: false });
        doc.moveDown(0.3);
      }
    }

    // Follows the content rather than pinning to the page bottom -- with a
    // variable amount of testing/PR data, an absolute bottom position can
    // fall outside the printable margin and force a spurious blank page.
    doc.moveDown(2);
    doc.fontSize(8).fillColor(GREY).text("Generated by Forge");

    doc.end();
  });
}
