import PDFDocument from "pdfkit";

export interface TrainingHistoryRow {
  date: string;
  exerciseName: string;
  isCorrective: boolean;
  setNumber: number;
  reps: string | null;
  weight: string | null;
  weightUnit: string | null;
  weightMode: string;
  rpe: number | null;
  notes: string | null;
}

function csvField(value: string | number | null | undefined) {
  const str = value == null ? "" : String(value);
  return /[",\n]/.test(str) ? `"${str.replace(/"/g, '""')}"` : str;
}

function formatLoad(row: TrainingHistoryRow) {
  if (row.weightMode === "bodyweight") return "Bodyweight";
  if (row.weightMode === "band") return row.weight ? `${row.weight} band` : "Band";
  if (row.weightMode === "box") return row.weight ? `${row.weight} ${row.weightUnit ?? "in"} box` : "Box";
  return row.weight ? `${row.weight} ${row.weightUnit ?? "lbs"}` : "";
}

export function buildTrainingHistoryCsv(rows: TrainingHistoryRow[]): string {
  const header = ["Date", "Exercise", "Type", "Set", "Reps", "Load", "RPE", "Notes"];
  const lines = [header.join(",")];
  for (const row of rows) {
    lines.push(
      [
        csvField(row.date),
        csvField(row.exerciseName),
        csvField(row.isCorrective ? "Corrective" : "Lift"),
        csvField(row.setNumber),
        csvField(row.reps),
        csvField(formatLoad(row)),
        csvField(row.rpe),
        csvField(row.notes),
      ].join(","),
    );
  }
  return lines.join("\n");
}

const ORANGE = "#F65B23";
const DARK = "#111111";
const GREY = "#666666";

/** Groups the flat set-level rows back into one section per training day so
 * the PDF reads like a logbook rather than a raw table -- the CSV stays flat
 * since spreadsheets are the ones that want one-row-per-set. */
export function buildTrainingHistoryPdf(
  athleteName: string,
  rows: TrainingHistoryRow[],
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "LETTER", margin: 50 });
    const chunks: Buffer[] = [];
    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    doc.rect(0, 0, doc.page.width, 90).fill(ORANGE);
    doc.fillColor("#ffffff").fontSize(24).font("Helvetica-Bold").text("FORGE", 50, 30);
    doc.fontSize(10).font("Helvetica").text("Full Training History", 50, 60);

    doc.moveDown(3);
    doc.fillColor(DARK).fontSize(20).font("Helvetica-Bold").text(athleteName);
    doc.fillColor(GREY).fontSize(10).font("Helvetica").text(`${rows.length} sets logged`);
    doc.moveDown(1);

    const byDate = new Map<string, TrainingHistoryRow[]>();
    for (const row of rows) {
      if (!byDate.has(row.date)) byDate.set(row.date, []);
      byDate.get(row.date)!.push(row);
    }
    const dates = Array.from(byDate.keys()).sort((a, b) => b.localeCompare(a));

    const pageBottom = doc.page.height - doc.page.margins.bottom;

    for (const date of dates) {
      if (doc.y > pageBottom - 60) doc.addPage();

      doc.moveDown(0.8);
      doc.fillColor(ORANGE).fontSize(13).font("Helvetica-Bold").text(date);
      doc.moveTo(50, doc.y).lineTo(doc.page.width - 50, doc.y).strokeColor(ORANGE).stroke();
      doc.moveDown(0.4);

      const byExercise = new Map<string, TrainingHistoryRow[]>();
      for (const row of byDate.get(date)!) {
        if (!byExercise.has(row.exerciseName)) byExercise.set(row.exerciseName, []);
        byExercise.get(row.exerciseName)!.push(row);
      }

      for (const [exerciseName, sets] of byExercise) {
        if (doc.y > pageBottom - 30) doc.addPage();
        const setsSummary = sets
          .map((s) => {
            const load = formatLoad(s);
            const repsLoad = [s.reps, load].filter(Boolean).join(" @ ");
            return s.rpe != null ? `${repsLoad} (RPE ${s.rpe})` : repsLoad;
          })
          .join(", ");
        doc
          .fillColor(DARK)
          .fontSize(11)
          .font("Helvetica-Bold")
          .text(exerciseName, 50, doc.y, { continued: false });
        doc.fillColor(GREY).fontSize(10).font("Helvetica").text(setsSummary, 60);
        doc.moveDown(0.3);
      }
    }

    doc.moveDown(2);
    doc.fontSize(8).fillColor(GREY).text("Generated by Forge");

    doc.end();
  });
}
