/** The text of robots.txt and sitemap.xml, as pure functions of the route list.
 *
 * Split out of scripts/generate-seo-files.ts so a test can assert what the files SAY without
 * running the build: that every indexable route is in the sitemap and nothing else is, that the
 * session-gated prefixes are disallowed, and that no URL carries a trailing slash the server would
 * not answer at. The script is the one place that does the writing.
 */
import { PUBLIC_ROUTES, NOINDEX_PREFIXES, AUTHED_PREFIXES } from "./public-routes";

export const DEFAULT_ORIGIN = "https://forgeperformancesystems.com";

export function sitemapXml(origin: string, lastmod: string): string {
  const base = origin.replace(/\/$/, "");
  const indexable = PUBLIC_ROUTES.filter((r) => r.index);
  if (indexable.length === 0) throw new Error("Refusing to write an empty sitemap");
  // One date for the whole build rather than a per-route timestamp: these pages are all generated
  // from the same commit, so per-page modification dates would be invented precision.
  const urls = indexable
    .map(
      (r) =>
        `  <url>\n    <loc>${base}${r.path}</loc>\n    <lastmod>${lastmod}</lastmod>\n    <priority>${(r.priority ?? 0.5).toFixed(1)}</priority>\n  </url>`,
    )
    .join("\n");
  return `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls}\n</urlset>\n`;
}

export function robotsTxt(origin: string): string {
  const base = origin.replace(/\/$/, "");
  // No trailing slash: "Disallow: /reset-password" matches the token URLs too, where
  // "/reset-password/" would match only subpaths and let the actual page through -- which is the
  // only form it ever appears in.
  //
  // Belt and braces alongside the per-page noindex tag, because they cover different things:
  // robots.txt stops the crawl, the meta tag stops the indexing of anything reached another way
  // (a link in an email, say). Neither alone covers both.
  const authed = AUTHED_PREFIXES.map((p) => `Disallow: ${p}`).join("\n");
  const disallow = NOINDEX_PREFIXES.filter((p) => !AUTHED_PREFIXES.includes(p))
    .map((p) => `Disallow: ${p}`)
    .join("\n");
  const explicitlyExcluded = PUBLIC_ROUTES.filter((r) => !r.index)
    .map((r) => `Disallow: ${r.path}`)
    .join("\n");
  return `# Generated by scripts/generate-seo-files.ts -- edit shared/public-routes.ts, not this file.
User-agent: *
Allow: /

# Needs a session. A crawler gets a login redirect or JSON here, never a page.
${authed}

# Public but one-shot: token landings and per-athlete invite links.
${disallow}

# Public, but nothing to rank: the sign-in form, and signup while the beta cannot serve
# the traffic a search result would send it.
${explicitlyExcluded}

Sitemap: ${base}/sitemap.xml
`;
}
