/** Writes robots.txt and sitemap.xml into client/public/ from the one route list.
 *
 * Generated at build time rather than committed, because a hand-maintained sitemap is one that
 * silently goes stale: the page gets added, the XML does not, and nothing breaks loudly enough
 * for anyone to notice.
 *
 * RUN THROUGH tsx SO IT IMPORTS THE REAL LIST. The first version of this parsed
 * shared/public-routes.ts with a regex over the source text, to avoid adding a build step for
 * one small array. That broke the moment the movement-library pages were appended to the array
 * programmatically instead of being typed out as literals -- the regex saw the literals and
 * missed four real pages, which is precisely the silent drift the generated sitemap exists to
 * prevent. Importing the module costs a `tsx` invocation and cannot be wrong about what is in it.
 */
import fs from "node:fs";
import path from "node:path";
import { PUBLIC_ROUTES, NOINDEX_PREFIXES } from "../shared/public-routes";

const outDir = path.resolve(import.meta.dirname, "..", "client", "public");
const origin = (process.env.VITE_PUBLIC_ORIGIN || "https://forgeperformancesystems.com").replace(/\/$/, "");

const indexable = PUBLIC_ROUTES.filter((r) => r.index);
if (indexable.length === 0) throw new Error("Refusing to write an empty sitemap");

// One date for the whole build rather than a per-route timestamp: these pages are all generated
// from the same commit, so per-page modification dates would be invented precision.
const today = new Date().toISOString().slice(0, 10);

const urls = indexable
  .map(
    (r) =>
      `  <url>\n    <loc>${origin}${r.path}</loc>\n    <lastmod>${today}</lastmod>\n    <priority>${(r.priority ?? 0.5).toFixed(1)}</priority>\n  </url>`,
  )
  .join("\n");

fs.writeFileSync(
  path.join(outDir, "sitemap.xml"),
  `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls}\n</urlset>\n`,
);

// No trailing slash: "Disallow: /reset-password" matches the token URLs too, where
// "/reset-password/" would match only subpaths and let the actual page through -- which is the
// only form it ever appears in.
//
// Belt and braces alongside the per-page noindex tag, because they cover different things:
// robots.txt stops the crawl, the meta tag stops the indexing of anything reached another way
// (a link in an email, say). Neither alone covers both.
const disallow = NOINDEX_PREFIXES.map((p) => `Disallow: ${p}`).join("\n");
const explicitlyExcluded = PUBLIC_ROUTES.filter((r) => !r.index)
  .map((r) => `Disallow: ${r.path}`)
  .join("\n");

fs.writeFileSync(
  path.join(outDir, "robots.txt"),
  `# Generated by scripts/generate-seo-files.ts -- edit shared/public-routes.ts, not this file.
User-agent: *
Allow: /
${disallow}

# Public, but nothing to rank: one-shot token pages, and signup while the beta cannot serve
# the traffic a search result would send it.
${explicitlyExcluded}

Sitemap: ${origin}/sitemap.xml
`,
);

console.log(
  `SEO files written: ${indexable.length} indexable routes, ${NOINDEX_PREFIXES.length} disallowed prefixes.`,
);
